In [1]:
from scipy.io import arff
import pandas as pd
from sklearn.model_selection import train_test_split
import os

In [2]:
#os.chdir("/home/szekeres/Dokumentumok/RightWhaleCalls")
!pwd

/home/szekeres/Dokumentumok/RightWhaleCalls

In [3]:
SEED = 2023

In [4]:
# Load ARFF files
data_train, meta = arff.loadarff('RightWhaleCalls_TRAIN.arff')
data_test, meta = arff.loadarff('RightWhaleCalls_TEST.arff')

In [5]:
#meta

In [6]:
# Convert to a Pandas DataFrame if needed
df_train = pd.DataFrame(data_train)
df_test = pd.DataFrame(data_test)

In [7]:
df_train.head()

,att1,att2,att3,att4,att5,att6,att7,att8,att9,att10,...,att3992,att3993,att3994,att3995,att3996,att3997,att3998,att3999,att4000,class
0,-0.005524,-0.011993,0.005127,0.007996,0.002716,0.000854,-0.009460,-0.005707,0.011993,-0.006012,...,0.003387,0.002808,0.003967,-0.002380,-0.003510,0.001434,-0.009125,-0.005829,0.006256,b'RightWhale'
1,-0.000854,0.001495,-0.004822,-0.000244,0.005432,0.006165,-0.002197,-0.010437,0.001282,0.011505,...,-0.002777,0.005615,-0.003510,-0.007477,0.004242,0.004913,0.003662,-0.007599,0.001892,b'RightWhale'
2,0.003143,0.004944,0.001160,-0.003540,-0.001343,-0.000885,-0.000763,0.000122,0.003021,-0.004883,...,-0.004089,0.001312,0.005127,-0.003326,0.000275,0.000275,0.002594,0.010254,-0.003876,b'RightWhale'
3,-0.001770,-0.001068,0.004425,-0.000977,-0.004242,0.002838,0.001282,-0.004303,0.001709,-0.000183,...,0.000885,0.000183,-0.000763,-0.003296,-0.001587,0.003540,0.001221,-0.001831,-0.001038,b'RightWhale'
4,0.008606,-0.001740,-0.003906,-0.003601,0.007263,0.001129,-0.013885,0.014160,0.012299,-0.016327,...,-0.000061,-0.004059,0.002625,0.005310,0.002869,-0.001709,-0.011444,0.007080,0.005859,b'RightWhale'

In [8]:
targets = df_train['class'].unique()
targets

array([b'RightWhale', b'NoWhale'], dtype=object)

In [9]:
target_values_dict = {}
for i, name in enumerate(targets):
    target_values_dict[name] = i

In [10]:
target_values_dict

{b'RightWhale': 0, b'NoWhale': 1}

In [11]:
df_train["class"] = df_train["class"].replace(target_values_dict)
df_test["class"] = df_test["class"].replace(target_values_dict)
df_train.head()

,att1,att2,att3,att4,att5,att6,att7,att8,att9,att10,...,att3992,att3993,att3994,att3995,att3996,att3997,att3998,att3999,att4000,class
0,-0.005524,-0.011993,0.005127,0.007996,0.002716,0.000854,-0.009460,-0.005707,0.011993,-0.006012,...,0.003387,0.002808,0.003967,-0.002380,-0.003510,0.001434,-0.009125,-0.005829,0.006256,0
1,-0.000854,0.001495,-0.004822,-0.000244,0.005432,0.006165,-0.002197,-0.010437,0.001282,0.011505,...,-0.002777,0.005615,-0.003510,-0.007477,0.004242,0.004913,0.003662,-0.007599,0.001892,0
2,0.003143,0.004944,0.001160,-0.003540,-0.001343,-0.000885,-0.000763,0.000122,0.003021,-0.004883,...,-0.004089,0.001312,0.005127,-0.003326,0.000275,0.000275,0.002594,0.010254,-0.003876,0
3,-0.001770,-0.001068,0.004425,-0.000977,-0.004242,0.002838,0.001282,-0.004303,0.001709,-0.000183,...,0.000885,0.000183,-0.000763,-0.003296,-0.001587,0.003540,0.001221,-0.001831,-0.001038,0
4,0.008606,-0.001740,-0.003906,-0.003601,0.007263,0.001129,-0.013885,0.014160,0.012299,-0.016327,...,-0.000061,-0.004059,0.002625,0.005310,0.002869,-0.001709,-0.011444,0.007080,0.005859,0

In [12]:
len(df_train), len(df_test)

(10934, 1962)

In [13]:
df = pd.concat([df_train, df_test], ignore_index=True)

In [14]:
len(df)

12896

In [15]:
df_train, df_test = train_test_split(df, stratify = df["class"], test_size = 0.2, random_state = SEED)

In [16]:
df_train

,att1,att2,att3,att4,att5,att6,att7,att8,att9,att10,...,att3992,att3993,att3994,att3995,att3996,att3997,att3998,att3999,att4000,class
8785,-0.000702,0.001282,0.007324,0.001770,-0.000488,-0.001953,-0.005615,0.000397,0.004425,-0.000580,...,0.007538,0.006226,0.002411,0.000366,0.004272,0.007172,0.005249,-0.000183,-0.000183,1
7077,0.160553,-0.101440,-0.265564,0.009491,0.116974,0.060944,0.023956,0.025604,0.059357,-0.066895,...,0.008179,0.000732,0.002075,0.004578,0.003571,0.013000,0.009918,-0.003052,0.002991,1
10994,0.009918,-0.004669,-0.004547,0.001343,-0.012970,-0.000488,0.008240,-0.005920,0.005981,0.006226,...,-0.006104,0.015320,-0.001007,-0.006317,0.009308,0.001556,0.003784,0.009583,-0.004547,0
12364,-0.014679,0.007599,-0.000214,0.003937,-0.003876,-0.004517,-0.005219,-0.000793,0.010406,-0.012177,...,0.001221,0.005157,0.005737,-0.013062,-0.004974,0.008728,-0.005371,-0.005951,0.010590,1
942,-0.000458,0.019775,0.004578,-0.012604,0.000641,-0.002350,0.016327,0.021240,-0.022614,-0.017578,...,0.002594,0.005829,0.013733,0.003265,0.000946,-0.004181,-0.010284,0.008545,0.009308,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9230,0.004211,-0.001495,-0.004425,0.005890,-0.011658,-0.004639,0.012207,-0.000549,0.000092,-0.003021,...,-0.002899,-0.000397,-0.000549,-0.007080,0.008118,0.004700,0.009460,-0.004333,-0.012024,1
3916,-0.005188,-0.003418,0.014862,-0.007660,-0.002808,0.005829,-0.008514,-0.003784,-0.000366,0.001556,...,0.001587,0.003326,-0.002625,-0.008698,0.003082,0.009796,-0.000214,0.005890,-0.005920,0
11322,-0.008118,0.003235,0.000153,-0.004822,0.006378,0.005524,-0.008942,-0.001892,0.006012,-0.004272,...,-0.001068,0.001740,0.001678,-0.009552,0.000092,0.009094,-0.008759,0.007599,-0.001678,0
11454,0.000946,0.004791,0.005615,0.003754,0.000275,-0.003052,-0.004242,-0.002716,-0.000824,-0.001740,...,0.000397,0.001801,0.002258,-0.000549,-0.002625,-0.000183,0.000397,-0.000244,0.002106,0
8890,0.019073,-0.023499,-0.000153,0.006287,-0.036499,0.029419,0.012512,-0.027679,0.021149,-0.000671,...,-0.053802,0.044464,0.010193,0.014282,-0.029327,0.006042,0.038574,-0.033600,0.059875,1

In [17]:
df_train.to_csv("train_whales.csv",sep=",",index=False)
df_test.to_csv("test_whales.csv",sep=",",index=False)

In [18]:
len(df_train),len(df_test)

(10316, 2580)

In [19]:
len(df_train)*0.25

2579.0